version: "3.7"
services: 
    postgres:
        image: postgres
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            APP_DB_USER: postgres
            APP_DB_PASS: postgres
            APP_DB_NAME: api

        ports:
            - 5431:5432
        volumes:
            - volume_container_users_api:/data/db
        networks: 
            - users-api-network
networks: 
    users-api-network:
        
volumes:
    volume_container_users_api: