service: users-app
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: sa-east-1
  memorySize: 128
  iamRoleStatement:
    - Effect: "Allow"
      Actions:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource:
        - "*"
package:
  exclude:
    - "**/*.ts"
    - "__test__/**"
    - "coverage/**"
    - "scripts/**"
    - ".vscode/**"
    - "src/**"
    - ".env"
functions:
  app:
    handler: lambda.handler
    timeout: 30
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
    vpc:
      securityGroupIds:
        - sg-d5dbbba3
      subnetIds:
        - subnet-f45d2dbd
        - subnet-65e1983e
        - subnet-db4e3cbd
    environment:
      DB_HOST: api.cefm0ozrdlns.sa-east-1.rds.amazonaws.com
      DB_NAME: api
      DB_PASSWORD: s7pctk3c
      DB_USERNAME: rootDev
      DB_PORT: 5432
      ENV: prod